<?php

namespace ContainerZjkCxx5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YSadlPJ.App\Controller\ContactController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YSadlPJ.App\\Controller\\ContactController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'contact' => ['privates', '.errored..service_locator.YSadlPJ.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.YSadlPJ": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'contact' => 'App\\Entity\\Contact',
        ]))->withContext('App\\Controller\\ContactController::show()', $container);
    }
}
