<?php

namespace ContainerBOxBj4Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9PXtK08.App\Controller\GroupController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.9PXtK08'] ?? $container->load('get_ServiceLocator_9PXtK08Service'));

        if (isset($container->privates['.service_locator.9PXtK08.App\\Controller\\GroupController::edit()'])) {
            return $container->privates['.service_locator.9PXtK08.App\\Controller\\GroupController::edit()'];
        }

        return $container->privates['.service_locator.9PXtK08.App\\Controller\\GroupController::edit()'] = $a->withContext('App\\Controller\\GroupController::edit()', $container);
    }
}
