<?php

namespace ContainerWHijLC9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9PXtK08Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9PXtK08' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9PXtK08'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'group' => ['privates', '.errored..service_locator.9PXtK08.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.9PXtK08": it needs an instance of "App\\Entity\\Group" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'group' => 'App\\Entity\\Group',
            'entityManager' => '?',
        ]);
    }
}
