<?php

namespace ContainerWHijLC9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9PXtK08.App\Entity\Group' shared service.
     *
     * @return \App\Entity\Group
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9PXtK08": it needs an instance of "App\\Entity\\Group" but this type has been excluded in "config/services.yaml".');
    }
}
