<?php

namespace ContainerJRg0l38;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FobyIDP.App\Controller\GroupController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FobyIDP.App\\Controller\\GroupController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'group' => ['privates', '.errored..service_locator.FobyIDP.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.FobyIDP": it needs an instance of "App\\Entity\\Group" but this type has been excluded in "config/services.yaml".'],
        ], [
            'group' => 'App\\Entity\\Group',
        ]))->withContext('App\\Controller\\GroupController::show()', $container);
    }
}
