<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90H57KE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90H57KE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container90H57KE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container90H57KE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container90H57KE\App_KernelDevDebugContainer([
    'container.build_hash' => '90H57KE',
    'container.build_id' => 'd20fd0ca',
    'container.build_time' => 1736697687,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container90H57KE');
